### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by min0609** [ZJUFanLab/scSpace#1]
Hi,
Thank you for this wonderful tool.
I downloaded setup.py and installed scSpace, but I got a AttributeError when I load the input files by scSpace.load_data.
Here is the command line I used to install scSpace:

```
conda create -n scspace python=3.8
conda activate scspace

pip3 install torch torchvision torchaudio

mkdir scSpace-master
cd scSpace-master
pip install -r requirements.txt

mkdir scSpace
touch scSpace/__init__.py
```

`python setup.py build`
running build
running build_py
creating build
creating build/lib
creating build/lib/scSpace
copying scSpace/__init__.py -> build/lib/scSpace

`python setup.py install`
running install
/Users/yoo/opt/anaconda3/envs/scspace/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer, pypa/build or
        other standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/Users/yoo/opt/anaconda3/envs/scspace/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer, pypa/build or
        other standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
creating scSpace.egg-info
writing scSpace.egg-info/PKG-INFO
writing dependency_links to scSpace.egg-info/dependency_links.txt
writing top-level names to scSpace.egg-info/top_level.txt
writing manifest file 'scSpace.egg-info/SOURCES.txt'
reading manifest file 'scSpace.egg-info/SOURCES.txt'
writing manifest file 'scSpace.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.9-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/scSpace
copying scSpace/__init__.py -> build/lib/scSpace
creating build/bdist.macosx-10.9-x86_64
creating build/bdist.macosx-10.9-x86_64/egg
creating build/bdist.macosx-10.9-x86_64/egg/scSpace
copying build/lib/scSpace/__init__.py -> build/bdist.macosx-10.9-x86_64/egg/scSpace
byte-compiling build/bdist.macosx-10.9-x86_64/egg/scSpace/__init__.py to __init__.cpython-38.pyc
creating build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying scSpace.egg-info/PKG-INFO -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying scSpace.egg-info/SOURCES.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying scSpace.egg-info/dependency_links.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying scSpace.egg-info/top_level.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/scSpace-1.0.0-py3.8.egg' and adding 'build/bdist.macosx-10.9-x86_64/egg' to it
removing 'build/bdist.macosx-10.9-x86_64/egg' (and everything under it)
Processing scSpace-1.0.0-py3.8.egg
Removing /Users/yoo/opt/anaconda3/envs/scspace/lib/python3.8/site-packages/scSpace-1.0.0-py3.8.egg
Copying scSpace-1.0.0-py3.8.egg to /Users/yoo/opt/anaconda3/envs/scspace/lib/python3.8/site-packages
Adding scSpace 1.0.0 to easy-install.pth file

Installed /Users/yoo/opt/anaconda3/envs/scspace/lib/python3.8/site-packages/scSpace-1.0.0-py3.8.egg
Processing dependencies for scSpace==1.0.0
Finished processing dependencies for scSpace==1.0.0

After the installation is finished, I tried to load input files with scSpace.load_data, but it gave me an AttributeError.
```
import scSpace
import scanpy as sc
import matplotlib.pyplot as plt
import matplotlib.colors as clr
import numpy as np
from sklearn.metrics import adjusted_rand_score
import random
import torch
import warnings
warnings.filterwarnings("ignore")
sc_data_dir = 'toy_inputs/demo_sc_data.csv'
sc_meta_dir = 'toy_inputs/demo_sc_meta.csv'
st_data_dir = 'toy_inputs/demo_st_data.csv'
st_meta_dir = 'toy_inputs/demo_st_meta.csv'
sc_obj, st_obj = scSpace.load_data(sc_data_path=sc_data_dir, sc_meta_path=sc_meta_dir, st_data_path=st_data_dir, st_meta_path=st_meta_dir)
```
AttributeError: module 'scSpace' has no attribute 'load_data'

I think the scSpace package is not installed completely. Could you please suggest a way to solve the problem?

Thanks!

**Comment by ForwardYang98** [comment]
Hi, sorry for responding you so late. You need download the whole `scSpace-master` zip not only the `setup.py` file, and then unzip this file to install scSpace.

**Comment by min0609** [comment]
Thank you for your help!
