### ISSUE TITLE
Lack of pre-processing

### ISSUE THREAD

**Issue by QingJun3** [ZJUFanLab/scSpace#2]
The DLPFC data downloaded from the google drive you provided does not match the data downloaded directly from spatialLIBD. 
For example, 151674, downloaded from google drive is 23113 * 3636 and 151674_filtered_feature_bc_matrix.h5 downloaded from spatialLIBD is 33538 * 3673, but you do not mention the relevant preprocessing in your paper or code.

**Comment by ForwardYang98** [comment]
For spots, we filtered those with "NA" layer labels; For genes, we converted the Ensembl ID to gene symbol using the biomaRt R package first and then revised and filtered genes according to NCBI Gene symbols updated in June 19, 2022.
