### ISSUE TITLE
about preprocessing

### ISSUE THREAD

**Issue by wyw-dlut** [ZJUFanLab/scSpace#3]
thx for ur sharing. I met some problems during reproducing this. I found that the preprocessing will take a long time. So could u tell me how long you spent on the preprocessing.

**Comment by ForwardYang98** [comment]
Hi, sorry for replying to you so late. scSpace's pre-processing steps are based on the standard workflow of scanpy (including normalization and find variable genes), and the running time is determined by the size of the data set itself (typically tens of seconds to several minutes).
